# Generated by Django 4.0.4 on 2022-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='title',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AddField(
            model_name='plus500',
            name='url_to',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='plus500',
            name='url_from',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
