# Generated by Django 3.2.13 on 2022-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0002_plus500_title_plus500_url_to_alter_plus500_url_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_rating', models.IntegerField()),
                ('domain_traffic', models.IntegerField()),
                ('organic_keywords', models.IntegerField()),
                ('referringDomains_backlinks_ratio', models.IntegerField()),
                ('domain_rating_priority', models.IntegerField()),
                ('domain_traffic_priority', models.IntegerField()),
                ('organic_keywords_priority', models.IntegerField()),
                ('referringDomains_backlinks_ratio_priority', models.IntegerField()),
                ('avatrae', models.BooleanField(default=False)),
                ('robinhood', models.BooleanField(default=False)),
                ('etoro', models.BooleanField(default=False)),
                ('IG', models.BooleanField(default=False)),
                ('CMC_markets', models.BooleanField(default=False)),
                ('email_template', models.CharField(max_length=10000)),
            ],
        ),
    ]
