# Generated by Django 4.0.4 on 2022-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0003_settings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='competitor',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='plus500',
            name='refdomains',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plus500',
            name='traffic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
