# Generated by Django 4.0.4 on 2022-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0004_plus500_competitor_plus500_refdomains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_from', models.CharField(blank=True, max_length=250)),
                ('traffic', models.IntegerField(blank=True, null=True)),
                ('competitor', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
