# Generated by Django 3.2.13 on 2022-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0006_delete_traffic_trend_settings_table_is_commodities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_table',
            name='links_num',
            field=models.IntegerField(null=True),
        ),
    ]
