# Generated by Django 4.0.4 on 2022-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0006_delete_traffic_trend_settings_table_is_commodities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plus500',
            name='refdomains_backlinks_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
