# Generated by Django 4.0.4 on 2022-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0007_plus500_category_plus500_refdomains_backlinks_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plus500',
            name='refdomains_backlinks_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
