# Generated by Django 3.2.13 on 2022-05-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0008_plus500_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_table',
            name='is_commodities',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='is_crypto',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='is_finance',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='is_forex',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='is_leisure',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='is_news',
        ),
        migrations.RemoveField(
            model_name='settings_table',
            name='organic_keywords',
        ),
    ]
