# Generated by Django 3.2.13 on 2022-05-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0008_alter_plus500_refdomains_backlinks_ratio'),
        ('plus500', '0009_auto_20220521_1701'),
    ]

    operations = [
    ]
