# Generated by Django 4.0.4 on 2022-05-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0010_merge_20220522_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='url_domain',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
