# Generated by Django 4.0.4 on 2022-05-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0011_plus500_url_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plus500',
            name='ahrefs_rank',
        ),
    ]
