# Generated by Django 3.2.13 on 2022-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0012_remove_plus500_ahrefs_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails_Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(blank=True, max_length=250)),
                ('send_email', models.BooleanField(default=False)),
                ('email_template2', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
