# Generated by Django 4.0.4 on 2022-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0013_emails_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='contact_email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
