# Generated by Django 3.2.13 on 2022-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0014_plus500_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_table',
            name='organic_keywords_priority',
        ),
        migrations.AddField(
            model_name='settings_table',
            name='traffic_trend_priority',
            field=models.IntegerField(null=True),
        ),
    ]
