# Generated by Django 3.2.13 on 2022-06-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0015_auto_20220604_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_table',
            name='referringDomains_backlinks_ratio_priority',
            field=models.FloatField(null=True),
        ),
    ]
