# Generated by Django 3.2.13 on 2022-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0016_alter_settings_table_referringdomains_backlinks_ratio_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_table',
            name='referringDomains_backlinks_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='settings_table',
            name='referringDomains_backlinks_ratio_priority',
            field=models.IntegerField(null=True),
        ),
    ]
