# Generated by Django 3.2.13 on 2022-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0017_auto_20220604_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_table',
            name='referringDomains_backlinks_ratio',
            field=models.IntegerField(null=True),
        ),
    ]
