# Generated by Django 3.2.13 on 2022-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0018_alter_settings_table_referringdomains_backlinks_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_table',
            name='email_template',
            field=models.TextField(null=True),
        ),
    ]
