# Generated by Django 3.2.13 on 2022-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0019_alter_settings_table_email_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_table',
            name='traffic_trend_priority',
        ),
        migrations.AlterField(
            model_name='settings_table',
            name='email_template',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
