# Generated by Django 3.2.13 on 2022-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0020_auto_20220604_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails_sending',
            name='email_template2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='settings_table',
            name='email_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
