# Generated by Django 3.2.13 on 2022-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0021_auto_20220607_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='email_template2',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='plus500',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emails_sending',
            name='email_template2',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='settings_table',
            name='email_template',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
