# Generated by Django 4.0.4 on 2022-06-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0022_auto_20220607_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails_Sending',
        ),
    ]
