# Generated by Django 4.0.4 on 2022-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0023_delete_emails_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus500',
            name='traffic_top10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plus500',
            name='traffic_top3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
