# Generated by Django 3.2.13 on 2022-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus500', '0024_plus500_traffic_top10_plus500_traffic_top3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_table',
            name='email_template',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
